### ISSUE TITLE
[SUGGESTION] Ability to change the selected variant

### ISSUE THREAD

**Issue by dx-rift** [Tria-Studio/TRIA-Issues#100]
**Is your feature request related to a problem? Please describe.**
Currently, if the map has any variants, the game picks one variant for the round. While this can be utilised in a few ways, my problem is that you're stuck with that variant until the round ends.

**Describe the solution you'd like**
I think you should be able to change variants through the MapScript (like a MapLib function that gets rid of the current variant and changes to a random variant). It would do good for more randomised gameplay and I think that it would let variants be utilised more.

**Comment by KryptonForce102** [comment]
Isn’t this the point of a variant? To be chosen once

**Comment by Rob07erto** [comment]
I mean it could help during testing of maps but whatevee its closed

**Comment by TheRealSuper678** [comment]
> I mean it could help during testing of maps but whatevee its closed

just remove the rest of the variants if u wanna test one of them
