### ISSUE TITLE
[BUG] Reload Map Not Working

### ISSUE THREAD

**Issue by TechnocraticAviation** [Tria-Studio/TRIA-Issues#101]
**Describe the bug**
Reloading maps does not work. When clicked, the loaded map list is cleared even though it displays the currently loaded maps, so the map kit is loaded instead.

**To Reproduce**
1. Load a map using its ID
2. Click on 'Reload Maps'
3. Enter the lift to play the next map

**Expected behavior**
Reloading maps should re-insert the updated maps instead of clearing the map list behind the display.

**Screenshots**
N/A

**Hardware Inform - Device: 
 - Device: HP Pavilion Gaming Laptop
 - OS: Windows 10
 - Version: 0.9(.1) stable

**Additional context**
To play the reloaded maps again, re-insert them with their respective IDs.

**Comment by KryptonForce102** [comment]
Most likely the web server

**Comment by TechnocraticAviation** [comment]
> Most likely the web server

I'm not sure, reloading with the ID always works first try

**Comment by KryptonForce102** [comment]
> > Most likely the web server
> 
> I'm not sure, reloading with the ID always works first try

My bad completely misunderstood. Will check code soon

**Comment by grif-0** [comment]
I do not think reloading maps needs the webserver and can't really see any reason it would need it

**Comment by Ethan76167** [comment]
fixed
