### ISSUE TITLE
[BUG] Load same map multiple times

### ISSUE THREAD

**Issue by KimOsono** [Tria-Studio/TRIA-Issues#102]
**Describe the bug**
You can load the same map multiple times

**To Reproduce**
1. Type in a map ID
2. Put a space after the ID (you can put as many as you want)

**Expected behavior**
After loading in the map for the first time it should load a duplicate if you have a space and the end of the ID

**Screenshots**
https://prnt.sc/eXqJaqcBySsj

**Hardware Information**
 - Device: Computer
 - OS: Windows 11
 - Version 0.9

**Comment by azzzertyy** [comment]
just dont press space
