### ISSUE TITLE
[BUG] Map reloads

### ISSUE THREAD

**Issue by Jaylxnn** [Tria-Studio/TRIA-Issues#103]
**Describe the bug**
When the map takes long to long, it changes the map but the lighting doesn't change at all, it'll be the previous' map lighting.

**To Reproduce**
1. Play a Map that has a lot of parts & wait for it to choose a different map
2. You can see that the lighting of the map is from the old one.

**Expected behavior**
When refreshing the map, the new map should have the appropriate lighting.

**Screenshots**
None.

**Hardware Information**
 - Device: PC
 - OS: WIN11
 - Version: stable

**Additional context**

**Comment by RadicalRadio** [comment]
I've seen some reports of this bug popping up. Does this happen to certain maps, or is this universal across the game? From my couple of rounds in public servers, I couldn't reproduce the bug, but I'll look into it
also @SunzyVale it's a bug, not a feature request lol

**Comment by SunzyVale** [comment]
@RadicalRadio oh my bad heh

Though the solution @Jaylxnn made needs a bit of rework even though I myself can't find any alternative solutions for it.
Anyway does the bug happen frequently or rarely? I haven't encountered nor heard of the bug

**Comment by Jaylxnn** [comment]
@RadicalRadio @SunzyVale Lol, my apologies for the bad wording & long responding time. This usually happens with servers more than 14+ players & maps with a lot of instances/parts.

**Comment by Ethan76167** [comment]
fixed?
