### ISSUE TITLE
funny gilch

### ISSUE THREAD

**Issue by theguyidot** [Tria-Studio/TRIA-Issues#104]
![RobloxScreenShot20221010_205015331](https://user-images.githubusercontent.com/115518962/194988985-2787f6cc-9393-4f6a-9379-4f5c22ed5330.png)
funny

**Comment by RadicalRadio** [comment]
There's not enough information for anyone to know what's going on here and how we could reproduce this (plus you didn't even follow the format)

**Comment by SunzyVale** [comment]
Additionally, we all know this bug already ever since months ago
And, it's a map bug

**Comment by grif-0** [comment]
Please follow the format next time as it’s hard to fix bug when all we know about it is “funny”. This is also a map bug which map bugs should be brought to the map dev rather than here.
