### ISSUE TITLE
No whitelist button...

### ISSUE THREAD

**Issue by Pozuria** [Tria-Studio/TRIA-Issues#105]
**Describe the bug**
Well, there's no whitelist button. Just that.

**To Reproduce**
1. Go to the main menu
2. Click on search icon
3. You see there is no whitelist button.
4. Map developers are doomed.

**Expected behavior**
Seeing the whitelist button.

**Screenshots**
![image_2022-10-11_154146855](https://user-images.githubusercontent.com/115537341/195041891-1efca126-fc03-4b56-a089-c04a4fd83106.png)

**Hardware Information**
 - Device: Windows 10 Pro
 - OS: 19044.2006
 - Version 21H2

**Additional context**
Please add it back.

**Comment by RadicalRadio** [comment]
This isn't a bug, this is currently because the webserver hasn't been migrated - stuff like publishing/whitelisting and searching has been down for a bit now.
If you have an older already whitelisted model that you don't need, you can update your model under that slot
