### ISSUE TITLE
Lush Remnant's fall debris here ruins flow of map

### ISSUE THREAD

**Issue by DONUTSLM** [Tria-Studio/TRIA-Issues#106]
Like in the video, when the button is pressed, the platforms fall and block the slide. This ruins the player's time and makes it almost impossible to make it to the end without dying. The easiest solutions to this would be to remove the slide or make the platforms CanCollide false when they fall so that they fall through the floor.

https://user-images.githubusercontent.com/75456372/196454406-3a6fd021-5b9c-4edc-adce-341d4f5a84e8.MOV

**Comment by RayhanahyaR** [comment]
1. If I remember correctly, Mar (creator) has said that the platforms should have cancollide false, you’ll just have to wait for the map model to be updated.
2. This is a map bug, it shouldn’t be on the GitHub, ask the creator (Mar) about this. also why does this have suggestion label
3.

**Comment by RayhanahyaR** [comment]
1. If I remember correctly, Mar (creator) has said that the platforms should have cancollide false, you’ll just have to wait for the map model to be updated.
2. This is a map bug, it shouldn’t be on the GitHub, ask the creator (Mar) about this. also why does this have suggestion label
