### ISSUE TITLE
[SUGGESTION] Increase the max time limit from 7 mins to 15mins

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/TRIA-Issues#11]
name: Feature request
about: Map max time limit
title: "Increase the max time limit from7 mins to 15 mins"
labels: suggestion
assignees: ''

Gauntlet maps have always been an idea I've seen floating around the TRIA discord every now and then, and thinking about them I think enabling these would allow for fun maps to exist (for example, the entire dystopian future chapter or the entire monochrome expansion). Yeah they might lag but I don't expect many of these maps to exist, other than peoples entire timelines in one map.

This doesn't solve any critical errors or flaws with the core gameplay loop of TRIA.os, but would enable creators to combine maps of theirs into one long gauntlet as a challenge for players looking for other stuff to do in the game. The increase of time from 7 mins to 15 mins would allow for longer gauntlet maps to be made.

**Comment by Ethan76167** [comment]
I'm yet to see a map that is 7 mins, I see no point in this

**Comment by azzzertyy** [comment]
sure

**Comment by Ethan76167** [comment]
On second thought I see no reason why we can't just remove the limit, default will still be 7mins however people can override this with the MaxTime Value
