### ISSUE TITLE
Map loading throws player immediately into the round

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/TRIA-Issues#12]
**Describe the bug**
Pretty straight forward. As soon as the map is finished loading, it throws the players into the round whether or not people even understand whats going on.

**To Reproduce**
1. put a map in the map list
2. enter the lift

**Expected behavior**
A short intermission would happen as players are in the spawn area of the map with the name showing, and then the round starting after 1-2 seconds.

**Screenshots**
N/A

**Hardware Information**
N/A

**Additional context**
This bug makes it increasingly difficult and annoying to play harder difficulty maps, especially ones with tight spawn rooms. This bug has heavily decreased my overall enjoyment of TRIA.os as many popular and fun maps are more challenging to play. If it makes it more annoying for me, I cant imagine what newer and less skilled players may think.

**Comment by Ethan76167** [comment]
@azzzertyy

**Comment by grif-0** [comment]
this bug effects multiplayer greatly

**Comment by Ethan76167** [comment]
loading screen planned + round changes

**Comment by Ethan76167** [comment]
this might be actually fixed now
