### ISSUE TITLE
[BUG]Round issue or something

### ISSUE THREAD

**Issue by JackDoeaw** [Tria-Studio/TRIA-Issues#121]
**Describe the bug**
The map just fails to load and you get stuck
only way to fix is by rejoining
(this happens to everyone that was in the round btw)

**To Reproduce**
1. random

**Expected behavior**
Play the level normally

**Screenshots**

https://user-images.githubusercontent.com/53980898/197435033-5b497340-3588-4e5e-9d3f-6cf324864992.mp4

**Hardware Information**
 - Device: [PC]
 - OS: [WIN11]
 - Version [TESTING]

**Additional context**
none

**Comment by KryptonForce102** [comment]
Will look into it, most likely something with setting up the round as it mentions it there

**Comment by KryptonForce102** [comment]
Should be fixed, will get QA to test once map loading is fixed.

**Comment by KryptonForce102** [comment]
Okay nevermind that one, round breaking bug is fixed, going to figure out why oxygen breaks.

**Comment by KryptonForce102** [comment]
Roblox bug
