### ISSUE TITLE
[BUG]group buttons

### ISSUE THREAD

**Issue by JackDoeaw** [Tria-Studio/TRIA-Issues#123]
**Describe the bug**
well 
you start the map with alot of people
group button at 2
everyone dies
im solo
group button still counts 2 people

**To Reproduce**
1. any map with group buttons
2. play with enough people (i have like 12 ppl)
3. group button is at 1 after you pressed it being solo

**Expected behavior**
button activate

**Screenshots**
3 videos

https://user-images.githubusercontent.com/53980898/197608890-312eba0f-7a64-4c79-a92f-412416bafac8.mp4
https://user-images.githubusercontent.com/53980898/197608991-7b5a24dc-113d-48a4-9b0a-9a32525c0668.mp4
https://user-images.githubusercontent.com/53980898/197609223-610fc402-19e2-4417-9b44-157d32714fe8.mp4

**Hardware Information**
 - Device: [PC/Desktop]
 - OS: [WIN11]
 - Version: [STABLE]

**Additional context**
please fix this asap as this makes maps unbeatable in public servers

**Comment by Ethan76167** [comment]
can I get a video?

**Comment by KryptonForce102** [comment]
0.9.2
