### ISSUE TITLE
[BUG]No default kit when pressed "load default"

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#124]
**Describe the bug**
No default kit when pressed "load default" see attachment Number 1

**To Reproduce**
1. Open TRIA.OS 0.9. HLUPDT
2. Click the Map Loading button
3. Click the "Load Default" button 

Literally in the name to load default kit

**Hardware Information**
 - Device: Pavilion 15 ec0003ca
 - OS: Windows 11 Home Edition
 - Version: Release 0.9 Halloween Update

Attachment 1: https://cdn.discordapp.com/attachments/950152108559183892/1034237765921022042/Roblox_2022-10-24_18-43-42.mp4

**Comment by KryptonForce102** [comment]
Load default is supposed to load the default maps (e.g. the ones that are in public servers). I don't think this works right now due to the webserver.

**Comment by KryptonForce102** [comment]
Going to keep this open just until webserver is done.
