### ISSUE TITLE
[BUG]F2 (spectate keybind) broken

### ISSUE THREAD

**Issue by JackDoeaw** [Tria-Studio/TRIA-Issues#130]
**Describe the bug**
you press F2 and instead of the spectate thing showing up, a black rectangle shows up

**To Reproduce**
1. Join game
2. Press F2

**Expected behavior**
quick spectate

**Screenshots**

https://user-images.githubusercontent.com/53980898/198152842-e1bcb1bf-8d52-451b-9e97-ccaef866790d.mp4

**Hardware Information**
 - Device: [PC/DESKTOP]
 - OS: [WIN11]
 - Version [STABLE]

**Additional context**
none

**Comment by Ethan76167** [comment]
Cause that's what the page looks like with no spectators, not a big
