### ISSUE TITLE
[BUG]LocalMapScript doesn't work in 0.10? (and as an addon, the F9 console keeps detecting your mouse)

### ISSUE THREAD

**Issue by RayhanahyaR** [Tria-Studio/Tria-Issues#143]
**Describe the bug**
I may just be stupid and could be theorizing, but the LocalMapScript may not be working in 0.10, it seems to have broken maps such as Umbralis and Lost Conscience along with it.

**To Reproduce**
1. Do literally anything in LocalMapScript
2. See if it works in TRIA
(also note, the F9 console is full of enum input stuff. help.)

**Expected behavior**
Something works. Instead the portal in Lost fail and the seamless teleport in Umbralis fails.

**Screenshots**
https://user-images.githubusercontent.com/104731980/206968916-41778878-0350-46aa-944c-05d3f2461505.mp4
https://user-images.githubusercontent.com/104731980/206969018-95752bbe-d8f5-40e6-8bb7-43f7ea6bdd98.mp4
![image](https://user-images.githubusercontent.com/104731980/206968737-222fbbb2-ea73-4657-a7fb-cca0924a9775.png)

**Additional context**
and yes, I checked the consoles, both of them. Nothing pops up.
and yeah i admit i should've probably tested in qa. ur allowed to laugh at me ethan/aze

**Comment by KryptonForce102** [comment]
@GlowingUmbreon this warn is ur thing what it is lol

**Comment by tactaillike** [comment]
I have a local script in Kneeling Shore that's supposed to change some of the lighting settings when a remoteevent is fired (doesn't use Lighting feature which was removed in 0.10), including the time of day and colorcorrection. I finally got the colorcorrection part working in 0.9.1, but now it doesn't work :(

**Comment by KryptonForce102** [comment]
Fixed
