### ISSUE TITLE
[BUG]Tank oxygen bar doesn't empty

### ISSUE THREAD

**Issue by RayhanahyaR** [Tria-Studio/Tria-Issues#144]
**Describe the bug**
The Oxygen Bar when a tank is activated doesn't empty, only the text works.

**To Reproduce**
1. Play MapKit and grab a tank
3. Walk into any fluid except lava

**Expected behavior**
Oxygen bar should slowly deplete until it is at 0, where it would become normal oxygen and go up to 100.

**Screenshots**
https://user-images.githubusercontent.com/104731980/206971784-ffc5bf32-4531-4e61-b186-e0af0775c770.mp4

**Additional context**
ok this looks even worse for me since we had already tested tanks. sorry ethan.

**Comment by KryptonForce102** [comment]
@GlowingUmbreon you last touched the hud what happened
