### ISSUE TITLE
[SUGGESTION] Option to show oxygen in cinematic mode

### ISSUE THREAD

**Issue by Accurate752** [Tria-Studio/Tria-Issues#147]
**Is your feature request related to a problem? Please describe.**
I personally like playing in cinematic mode, and due to some maps having swimming sections, i cant see how close i am to drowning.  

**Describe the solution you'd like**
Whenever you are swimming, you could either do one of these:
**A.** Have it so a simplistic and small swimming gui rise up into frame.
**B.** Have the first part of the main gui slide into frame, not including the buttons.

**Additional context**
This could be a togglable option, but i think personally it would add clutter to the settings.

**Comment by grif-0** [comment]
@Ethan76167 wasnt there a plan to make like a gradient border around the screen show for oxygen in cinematic mode

**Comment by grif-0** [comment]
will be in 0.11
