### ISSUE TITLE
[BUG] FPS Based wallrun speed(?)

### ISSUE THREAD

**Issue by fxrezful** [Tria-Studio/Tria-Issues#148]
**Describe the bug**
I was playing kneeling shore and suddenly noticed that I was faster on a wallrun on minimum graphics than maximum graphics

**To Reproduce**
1. Play kneeling shore (or any map with wallruns but I am not sure if this bug applies to all wallruns)
2. Compare the speed of yourself on a wallrun with low and high fps

**Expected behavior**
I expected the wallrun to have the same speed regardless of the fps

**Video**
https://streamable.com/u50f5e

**Hardware Information**
 - Device: PC
 - OS: Windows 10
 - Version stable

**Additional context**
deltaTime 😎

**Comment by Ethan76167** [comment]
@fxrezful what fps are you running at here

**Comment by fxrezful** [comment]
@Ethan76167 
Max graphics: ~150 fps
Min graphics: ~300 fps

**Comment by Ethan76167** [comment]
yeah so its related to 240-250fps and higher @GlowingUmbreon
