### ISSUE TITLE
[SUGGESTION] Expand zipline hitbox

### ISSUE THREAD

**Issue by RadicalRadio** [Tria-Studio/Tria-Issues#149]
**Is your feature request related to a problem? Please describe.**
This usually applies to converting maps from FE2CM to TRIA.os, but this can happen to any map. Ziplines become inconsistent due to FE2CM's ziplines having a hitbox much larger or the pole having the first zipline point too high up. This sometimes causes you to miss the zipline entirely.

**Describe the solution you'd like**
Right now, it's hard to walk onto the zipline and latch onto it and usually requires a jump onto the zipline. Simply put, extend the hitbox to make it a little easier to grasp on. (This doesn't apply to every zipline, so allowing hitbox sizes could also be an option, but I think just extending it will suit)

**Additional context**

**Comment by azzzertyy** [comment]
maybe we could add a manually placed hitbox for it like buttons

**Comment by KryptonForce102** [comment]
The hitbox is the first point of the zipline. You should be able to change it and make the hitbox bigger

**Comment by GlowingUmbreon** [comment]
> maybe we could add a manually placed hitbox for it like buttons

Eh they are already manual.

**Comment by RadicalRadio** [comment]
> The hitbox is the first point of the zipline. You should be able to change it and make the hitbox bigger

Ah, that makes sense. Thanks for the clarification!
