### ISSUE TITLE
Map Testing/Whitelisting

### ISSUE THREAD

**Issue by Cupheeddicee** [Tria-Studio/Tria-Issues#153]
Bug description:
Basically what this bug is about is that when I try to load a map on my Private Server, TRIA doesn't load the map.

Bug Reproduce:
1. Go to Map Manager
2. Click on Whitelist
3. Enter your map ID (It needs to be a model and be on marketplace)
4. Go to your Private Server or from a Friend
5. Load the ID of your map
6. Error may happen. It does not happen to everyone that tests its own map.

Error Behavior:
When trying to load your map and test it, TRIA instead does nothing instead.

I have no screenshot / video cause YouTube doesn't let me upload videos (Idk why)

**Hardware Information**
 - Device: PC
 - OS: Windows 10
 - Version: 21H2

Additional Text
This kept happening when I tried to test any other map that I made.

**Comment by basketcat** [comment]
> Whitelisting is up and working

It was actually my problem, map model didn't have MapScript and Settings on it. That's why it didn't work.
