### ISSUE TITLE
[BUG] Vivid 2D Section

### ISSUE THREAD

**Issue by betterert** [Tria-Studio/Tria-Issues#154]
On the first screen of the first 2D section of Vivid, the first walljump can be latched onto from the wrong side of the wall.

1. Enter the map Vivid.
2. Get to the first 2D section.
3. Get past the two walljumps of the first 2D section.
4. Run into the right side of the first walljump.

Normally, I would expect my avatar to run into the right side of the first walljump and fall down, not latching onto it.

https://prnt.sc/DfgE6IWAcO8t
This screenshot shows my avatar being latched onto the walljump, the small rectangle being pointed to on the right side of wall is my avatar.

 - Device: PC
 - OS: Windows 11
 - Version 0.10.0, it's just the one you get when you play the game normally? I don't know if it's testing or stable.
EDIT: It's version 0.10.0-Stable-2.

**Comment by Ethan76167** [comment]
enszo has made changes to the map so this isnt a problem anymore
