### ISSUE TITLE
[SUGGESTION]Ranged Variants

### ISSUE THREAD

**Issue by RayhanahyaR** [Tria-Studio/Tria-Issues#155]
**Is your feature request related to a problem? Please describe.**
Variants can only be a set amount of variants. So if you want to make something completely random, you'd have to make a lot of variants.

**Describe the solution you'd like**
Ranged variants. A variant can be set from a specific point to another specific point, like how roblox's math.random scripts work

**Additional context**
As an example:
Point A: 0, 10, 10
Point B: 0, -10, -10
This way there will be 400 different variations.

**Comment by Ethan76167** [comment]
support this

**Comment by grif-0** [comment]
@RayhanahyaR can  you give an example of a use case? Having a hard time understand what you mean
