### ISSUE TITLE
A way to properly delete  maps from the whitelist

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#16]
I want to delete alot of my maps from trias account and public. Due to that not being a feature i want one. I have tons of start of the ruining. Ruins trials, escape, crystal and even island tests i have whitelisyed and published tjat needs to be removed. And when added it it will help put a ton
Thanks
Roberto

**Comment by Ethan76167** [comment]
doesnt follow format

**Comment by Roberto070** [comment]
i did? idk. but please implement it

**Comment by Rob07erto** [comment]
oh kmon
