### ISSUE TITLE
[BUG]When in water, the music earrapes

### ISSUE THREAD

**Issue by DONUTSLM** [Tria-Studio/Tria-Issues#160]
**Describe the bug**
When a player's camera is in the water, the music gets earrape-y.

**To Reproduce**
Enter a map and go in water.

**Expected behavior**
I don't know what exactly was intended, but the music should become quieter and muffled when in water, not become earrape.

**Videos**
https://www.youtube.com/watch?v=iXLRL1_ZSDE&t=3m42s
https://www.youtube.com/watch?v=VX7x6TyA52s&t=1m11s

**Comment by azzzertyy** [comment]
i agree that it should be quieter but the ear-rapeyness is not in game, it is a fault of the recording software used for the video AFAIK, its peaking the microphone.

**Comment by Ethan76167** [comment]
^^
