### ISSUE TITLE
[SUGGESTION] MapLib:Rotate() method

### ISSUE THREAD

**Issue by coderheck** [Tria-Studio/Tria-Issues#168]
Always been using TweenService or CFrame operations to rotate a part/model in a map and it may cause some unwanted errors especially for unexperienced scripters who will mess something with the CFrame math operations or forgetting the :Play() function after a tween.

A solution to make our lives easier, I think, is to create a MapLib method specifically to rotate PVInstances.

Method syntax:
```lua
MapLib:Rotate(target: PVInstance, rotate: CFrame)
```

**Comment by grif-0** [comment]
the arguments of this function would essentially be identical to that of that to create a tween so I cant really see the point of this
