### ISSUE TITLE
[Bug] Button placement issue.

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/Tria-Issues#169]
**Describe the bug**
Ui placement is off in the administrator settings in 0.11. 

**To Reproduce**
1. Open TRIA 0.11 
3. Click on the setting buttons
4. Click the admin setting.
5. Checkout User Permission. 

**Expected behavior**
Ui to follow the normal behavior of the drop down settings.

**Screenshots**
![image](https://github.com/Tria-Studio/Tria-Issues/assets/48226111/ecb1413d-de15-418b-bc2d-c1837497fd75)

**Hardware Information**
 - Device: Acer Hellios
 - OS: Windows 11
 - Version: Beta/QA Ver

**Comment by Ethan76167** [comment]
intended
