### ISSUE TITLE
[SUGGESTION] Slide button shouldn't be present when sliding is disabled

### ISSUE THREAD

**Issue by RadicalRadio** [Tria-Studio/TRIA-Issues#17]
**Is your feature request related to a problem? Please describe.**
The button for sliding appears at all times, even when disabled, which is a little annoying considering mobile buttons. _(I'm not sure if this is a bug or wasn't implemented, so I put it here)_

**Describe the solution you'd like**
Making the button only appear on maps that have sliding enabled would be better, making the button only appear when needed, similar to the swim down button.

**Additional context**
![Screenshot_20220606-1231503](https://user-images.githubusercontent.com/104731777/172214797-6ad6ac74-0891-47e5-a734-67d68250f272.png)

**Comment by Ethan76167** [comment]
Could work something out

**Comment by Ethan76167** [comment]
0.8
