### ISSUE TITLE
[BUG]"Granted Permissions" text does not go away

### ISSUE THREAD

**Issue by RayhanahyaR** [Tria-Studio/Tria-Issues#171]
**Describe the bug**
When you are given map or admin permissions by the owner, the text does not vanish, instead staying on the screen

**To Reproduce**
1. Enter a VIP server with the Owner
2. The owner should give any sort of permission to the player

**Expected behavior**
Messages should vanish after a few seconds

**Screenshots**
![image](https://github.com/Tria-Studio/Tria-Issues/assets/104731980/e2400cc3-af17-4641-a827-727587e35c6f)

**Hardware Information**
 - Device: PC
 - Version master

**Comment by Ethan76167** [comment]
video

**Comment by grif-0** [comment]
should be fixed
