### ISSUE TITLE
[SUGGESTION] More types of buttons for unique gameplay

### ISSUE THREAD

**Issue by MADB0SS** [Tria-Studio/TRIA-Issues#18]
**Is your feature request related to a problem? Please describe.**
Sometimes unique ideas are difficult to make, and I believe more unique button styles could enhance gameplay experience and promote easy access to cool ideas without major scripting.

**Describe the solution you'd like**
I would specifically like to see multiple separate, interchangeable options/attributes.
First being a *button that is activated when you either click spacebar or another key bind that you can bind yourself.* It's basically just a normal button, except it only activates if you press said key bind while inside of the hitbox.

Next being buttons that do *not count for the exit region.* (I will refer to this as X mode) I know path buttons exist, but sometimes each path isn't planned to have equal button amounts and locations, so it becomes a challenge to space them out correctly. Not to mention, sometimes buttons could be optional. So, a button that doesn't count for reaching the exit would be very nice.

Third could be *invisible buttons*, which essentially just removes the button locator and click sound. X would always apply to these buttons. This could be used to create parts that you would normally jump on to have unique movement without an awkward button sound. This specific option could work very well with the following;

*Local buttons.* These are buttons that can ONLY be pressed by you, and other player's presses would not influence the button events connected to it. It is really quite self explanatory. X mode would be optional

Sorry for the long essay. I just think these added button features could spice up gameplay quite a lot.

**Comment by grif-0** [comment]
A button where you must press alt f4 to activate it

**Comment by Ethan76167** [comment]
I'm really not seeing any point in these, most of your suggestions feel like they would only be used once. We could definitely add something to activate a button from the MapLib though. 

`ButtonFeature:Activate(buttonNumber: number)` maybe idk?

Also, you can get rid of the button sound by setting the `PressedSound` to 0
