### ISSUE TITLE
[BUG] MapLib:ChangeMusic seems to play audio a couple seconds before the chosen time stamp

### ISSUE THREAD

**Issue by Accurate752** [Tria-Studio/TRIA-Issues#19]
**Describe the bug**
When using MapLib:ChangeMusic to skip ahead to a farther part of a song, it seems to sometimes start a little behind the chosen timestamp, then suddenly loop back to where the timestamp was chosen after about 10 seconds? I made a map to demonstrate this: 7124990288

**To Reproduce**
Create a map, with any approved audio, skipping ahead to another part in the song.
Play the map.

You can also load a map i made to showcase the bug, 7124990288.

**Expected behavior**
The song in the map starting exactly where i put the timestamp in ChangeMusic, and playing smoothly through the whole thing. The audio in the map above is intended to start 90 seconds into it, though it doesnt.

**Video**
(I dont think sending a direct link works, so heres a link of it on streamable)
https://streamable.com/vrn0g3

**Hardware Information**
 - Device: Computer
 - OS: Windows 10
 - Version: Stable

**Comment by Ethan76167** [comment]
Does this behaviour happen 100% of the time?

**Comment by Accurate752** [comment]
I think it might just be with a couple songs, the one i tested, Rock Thing had the bug, but when i changed it to some other songs, it worked as intended. It might just randomly happen with a couple songs is my guess. When i was testing it with Rock Thing, it happened every single time.

**Comment by Roberto070** [comment]
no for me i did it, before. and It does happen to me

**Comment by Rob07erto** [comment]
yea like i tested it now and yea

**Comment by Ethan76167** [comment]
Ok so from what I'm understanding, your trying to set the time position of a song using ` MapLib:ChangeMusic `, but the time position is being set a few seconds before the chosen timestamp?

**Comment by Accurate752** [comment]
Yeah, it also restarts at the correct time position after around 10 seconds, then goes through the song as intended.

**Comment by Ethan76167** [comment]
> Yeah, it also restarts at the correct time position after around 10 seconds, then goes through the song as intended.

I'm unable to reproduce this bug, both of my maps use `MapLib:ChangeMusic` and it works as intended.

Can you go into Studio and create a sound instance and set the `TimePosition` to the value you're trying to change it to, if it plays at the same TimePosition as ingame then this isn't a bug and your TimePosition argument is incorrect.

Also, can I ask you to post your script containing the usage of `MapLib:ChangeMusic` thanks
