### ISSUE TITLE
[UPDATE REQUEST] Mythereal 

### ISSUE THREAD

**Issue by Dzro04** [Tria-Studio/Tria-Issues#197]
MAP NAME: Mythereal 
SHORT ID: myth
MAP ID: 13472270573
IMAGE ID: 13555734238 
DIFFICULTY NUMBER: 4
OWNER ID: 1281444657
LATEST ASSET VERSION: 17564998825
VIDEO SHOWCASE: Mythereal V1: https://youtu.be/x3BqDM9ZO9M || Mythereal V2: https://www.youtube.com/watch?v=yXbR_9wljr4

REASON FOR UPDATE: Preparing for the map to get added into the main game, along with additional changes. 

# **FULL MAP CHANGELOG:**

## Added
 •  Design that more fits the theme of the map. 
 • Ambient SFX in different portions of the map.
 • One final speedrunning section in the map, before the player reaches the end.  

## Removed
  •  Unfit decorations that did not have a place in the map.

## Changed
 • The gameplay of the entire map.
 • Numerous detail improvements all around the entire map.

## Fixed
 • The awkward camera angles when players teleport from portals. 
 • Inconsistent pacing, and unstable gameplay unfit for the map's difficulty. 
 • Massive mountain safespot in the second section of the map. 
 • Unpolished, rushed feeling of the map.
 • Portions of the map that could cause confusion. 
 • Better visibility for sliding portions.

**Comment by grif-0** [comment]
changing the short ID to "myth" so its consistent will all short map ids
