### ISSUE TITLE
[SUGGESTION] For 1 player server, map loading should always wait for the player no matter how long it takes

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/TRIA-Issues#20]
**Is your feature request related to a problem? Please describe.**
For VIP servers with 1 player in them, kinda annoying how map loading can be skipped for what would be to not hold up the other players in the game. But if its just you in the server, why should it wait? Obviously if another player joins then map loading should probably skip if its taking too long but otherwise, I see no reason on why it cant wait.

**Describe the solution you'd like**
Map loading should not skip and start the round before the player is loaded in for 1 player servers

**Additional context**

**Comment by Ethan76167** [comment]
@azzzertyy @GlowingUmbreon Thoughts on this?

**Comment by azzzertyy** [comment]
good for me

**Comment by grif-0** [comment]
Will do tonight
