### ISSUE TITLE
[BUG] Player list UI is scaled wrong

### ISSUE THREAD

**Issue by Mafi12** [Tria-Studio/Tria-Issues#201]
**Describe the bug**
The player list UI is misaligned currently

**To Reproduce**
1. Enter the game
2. Open the player list

**Expected behavior**
Text size of the player list to be bigger and aligned correctly

**Screenshots**
Player list in 0.9
![image](https://github.com/Tria-Studio/Tria-Issues/assets/119030451/b1d45092-ed74-455e-9cc4-3fc8ff87db9e)

Player list in 0.10
![image](https://github.com/Tria-Studio/Tria-Issues/assets/119030451/aa97b8e9-132d-4223-891f-36f50974f240)

**Hardware Information**
 - Device: PC
 - OS: Windows 10
 - Version testing

**Additional context**
Some change made in 0.10 caused this to happen. Happens in both testing and stable.

**Comment by azzzertyy** [comment]
@Ethan76167 can you work on this one soon its always annoyed me

**Comment by grif-0** [comment]
its probably bugged me more ill check it out 

im pretty sure its because it uses scale

**Comment by grif-0** [comment]
fixed
