### ISSUE TITLE
[BUG]New physics can cause player to stagger in small walkways

### ISSUE THREAD

**Issue by RayhanahyaR** [Tria-Studio/Tria-Issues#203]
**Describe the bug**
If a player tries to walk through a gap, they'll stutter while going through. This did not happen in 0.10.

**To Reproduce**
1. Make a small walkway (the one I've used is 2 studs wide)
2. Test

**Expected behavior**
Player is expected to get through normally without any difficulties

**Screenshots**

**0.11/Testing**
https://github.com/Tria-Studio/Tria-Issues/assets/104731980/984a4352-445d-47eb-8032-1e645fb5f489
**0.10/Main game**
https://github.com/Tria-Studio/Tria-Issues/assets/104731980/2dfd1be4-6475-493e-ba78-0b6cf6a03ab1

**Hardware Information**
 - Device: Windows 10
 - OS: Windows
 - Version master

**Comment by grif-0** [comment]
not a bug
