### ISSUE TITLE
[BUG]Lightning acting weird

### ISSUE THREAD

**Issue by JackDoeaw** [Tria-Studio/Tria-Issues#208]
**Describe the bug**
Some maps have broken lightning, such as:
-Layers: way darker
-Monoscape: slightly orange
-Cubic void: slightly brighter
Theres likely more but i have not seen a ton of maps yet

**To Reproduce**
1. Play a map (?- that has some sort of custom lightning maybe?)
2. Pay attention to shadows, far away lights and brightness

**Expected behavior**
To be a normal lightning like in the videos/before the update
Layers > brighter 
Monoscape > no orange far away
Cubic void > darker

**Screenshots**
Monoscape: 
![image](https://github.com/Tria-Studio/Tria-Issues/assets/53980898/4e764644-76fa-4b0f-ba6b-d06d8caa01e9)

Layers: 
![image](https://github.com/Tria-Studio/Tria-Issues/assets/53980898/8f79e281-d4df-4b03-a518-9582b96bda7c)

Cubic void:
i do not have one atm

**Hardware Information**
 - Device: PC (Custom)
 - OS: [Windows11 beta build]
 - Version [stable]

**Additional context**
These lightning bugs did not happen before 0.11, so it's a bug that came with 0.11

**Comment by Ethan76167** [comment]
not a tria bug, this is a side effect of using a dependency and not correctly setting all lighting values
