### ISSUE TITLE
[BUG] Automatically Spawn in elevator setting not always working 

### ISSUE THREAD

**Issue by Shaadth** [Tria-Studio/TRIA-Issues#21]
While playing for a while sometimes you dont automatically spawn in the elevator it just puts you in normal spawn
 
It shows the elevator for a split second then spawns you in the lobby

If you wanna reproduce go play a map for a few minutes with the setting on and wait and see if you dont spawn in the elevator

**Comment by Ethan76167** [comment]
Might be a wise idea instead of just overwriting the player CFrame to instead move the main spawn depending on if the setting is enabled or not.

I'll get this done in 0.8

**Comment by Ethan76167** [comment]
> > Might be a wise idea instead of just overwriting the player CFrame to instead move the main spawn depending on if the setting is enabled or not.
> > I'll get this done in 0.8
> 
> not possible, the elevator and spawn are handled by the server.

Make it client sided?

**Comment by Ethan76167** [comment]
How should we go about this then
