### ISSUE TITLE
[BUG] walljump bug for mobile

### ISSUE THREAD

**Issue by ItsFor** [Tria-Studio/TRIA-Issues#213]
**Describe the bug**
If you were to make the walljump front side only, it disables it for mobile.

**To Reproduce**

**Expected behavior**
You should stick to the walljump on any device and not only pc.

**Screenshots**

**Hardware Information**
 - Version [e.g. testing/stable]
 - I know that it’s for mobile

**Additional context**

**Comment by Ethan76167** [comment]
Video or image proof is required for this right be looked into further

**Comment by Ethan76167** [comment]
fixed
