### ISSUE TITLE
[BUG]Title Here

### ISSUE THREAD

**Issue by baort** [Tria-Studio/TRIA-Issues#214]
**Describe the bug**
A clear and concise description of what the bug is. Must specify whether the bug is a bug with TRIA.os or the Mapmaking Plugin.
When you die and have the auto spectate on, it doesn't make the person automatically spectate someone else.
**To Reproduce**

**Expected behavior**
I expected that when you die with auto spectate on, you would spectate another person automatically.
**Screenshots**
I dont have any screenshots
**Hardware Information**
 - Version [e.g. testing/stable]

**Additional context**

**Comment by Ethan76167** [comment]
doesnt follow format, media needs to be provided
