### ISSUE TITLE
[BUG] Jumping off of ziplines not working on mobile

### ISSUE THREAD

**Issue by shee3eesh** [Tria-Studio/TRIA-Issues#216]
**Describe the bug**
This bug is with TRIA.os:
I believe the most recent update somehow causes mobile players to not be able to prematurely jump off of ziplines.
I have tested several different maps in which jumping from ziplines is a mechanic and it doesnt work in any of them (DREAMER, vell, ANTIVOID, MATRIX, etc.)

**To Reproduce**
To reproduce this, you would need to,
a.) Open your TRIA.os private server on a mobile device,
b.) Load the ID to one of the aforementioned maps,
and c.) Play the map until you get to a point where to continue you must jump off of a zipline before it ends. For whatever reason, it will not work.

**Expected behavior**
What should've happened is your character jumping off of the zipline with no problems.

**Hardware Information**
 - Device: iPad mini 5th generation
 - OS: iOS
 - Version: stable

**Comment by Ethan76167** [comment]
@shee3eesh video is a requirement

**Comment by shee3eesh** [comment]
managed to get a video:

https://github.com/Tria-Studio/Tria-Issues/assets/137780711/c5f0de51-5bad-4591-b590-3d0ee29a81de

**Comment by Ethan76167** [comment]
Now looking into this
