### ISSUE TITLE
[BUG] Lighting when loading into maps don't get shown. 

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#219]
**Describe the bug**
 When loading into maps the lighting effects don't get shown. (Check image no. 1, & 2)  

**To Reproduce**
1. Load a map like black aurora.
2. See error

**Expected behavior**
Check image number 2.

**Hardware Information**
 - Device: Acer Predator Helios 
 - OS: Windows 11
 - Version Stable

1.  Bug:
![image](https://github.com/Tria-Studio/Tria-Issues/assets/48226111/6739afc7-e523-46a3-887a-519d24e784d4)

2: Intended:
![image](https://github.com/Tria-Studio/Tria-Issues/assets/48226111/a3a357be-7244-49d6-ae12-3acb86ae16d7)

3: Error
![image](https://github.com/Tria-Studio/Tria-Issues/assets/48226111/689dff8c-0f87-4466-8921-7f53d5df8ae8)

**Comment by Ethan76167** [comment]
the post effects did load
thats why the player is monochrome
