### ISSUE TITLE
[SUGGESTION]Random NPC in TRIA OS

### ISSUE THREAD

**Issue by Ex7remeLOL** [Tria-Studio/TRIA-Issues#22]
**Is your feature request related to a problem? Please describe.**
Some random interactive NPC that spawns in TRIA OS lobby

**Describe the solution you'd like**
So for example, there might be 2-3 NPC spawn each day in different locations in the lobby, sometimes it can be randoms or sometimes it can be special people like Tria staff or others

**Additional context**
This is how I correctly use the template right?

**Comment by Ethan76167** [comment]
Pointless

**Comment by Rob07erto** [comment]
Dont we have 1 already?
