### ISSUE TITLE
[BUG] Rail and Zipline Leaning

### ISSUE THREAD

**Issue by KrazedKiefer** [Tria-Studio/TRIA-Issues#224]
The Bug:
When 0.11.1 was added to the game, the Grinding Rails feature and the Zipline Leaning were supposed to be added with the update, but when the update released the rail mechanic was no where to be found in the Map Kit and Zipline leaning isn't even working on ziplines.

To Reproduce:
1. Join Tria.os on the roblox website.
2. Load the Map Kit
3. Join the lift.
4. Go to the zipline and the error will appear.

Expected behavior:
Grinding Rail feature and working zipline leaning inside of the game/mapkit.

Screenshot:
![image](https://github.com/Tria-Studio/Tria-Issues/assets/113727968/dfc086f7-da10-49ee-b66e-073db1af1173)
I am pressing A and D, nothing is happening.
Hardware Information:
 - Device: Windows 10 PC
 - OS: WindowsOS
 - Version: Stable

**Comment by Ethan76167** [comment]
maps have to manually enable the feature
