### ISSUE TITLE
Lib:MovePart() to support Enum.EasingStyle

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/TRIA-Issues#23]
Currently, MovePart only allows for a linear easing style. However that's not bad, I think it can be better if you allow creators to give an easing style (optional, default is still linear) and have the move function follow said easing style.

This would give more power to the creators to give more naturalism, style, and make maps feel more immersive when lava doesn't always sharply increase and stop moving.

Yeah you could say "just use tweenservice" but then why does this function exist?

**Comment by grif-0** [comment]
And possible Enum.EasingDirection to go along with it*

**Comment by Ethan76167** [comment]
But tweenservice....

**Comment by Ethan76167** [comment]
Ok looking back at this I'd definitely want :EasePart() to be implemented assuming we return the actual tween that's playing.
With this being implemented we can efficiently have a way for a block of code to be ran after another part has finished moving

For example the following

```lua
Lib:MovePart(Map.Part1, Vector3.new(0, 5, 0), 5)
task.wait(5)
Lib:MovePart(Map.Part2, Vector3.new(0, 5, 0), 5)
```
Could be simplified into 

```lua
Lib:EasePart(Map.Part1, Vector3.new(0, 5, 0),TweenInfo.new(1, Enum.EasingStyle.Sine, Enum.EasingDirection.Out)).Completed:Wait()
--Do something else after the part stops moving
```
`Lib:MovePart() ` should remain untouched imo

**Comment by Rob07erto** [comment]
i would like tween service to be implements directly into Lib:MovePart

**Comment by Ethan76167** [comment]
> Ok looking back at this I'd definitely want :EasePart() to be implemented assuming we return the actual tween that's playing. With this being implemented we can efficiently have a way for a block of code to be ran after another part has finished moving
> 
> For example the following
> 
> ```lua
> Lib:MovePart(Map.Part1, Vector3.new(0, 5, 0), 5)
> task.wait(5)
> Lib:MovePart(Map.Part2, Vector3.new(0, 5, 0), 5)
> ```
> 
> Could be simplified into
> 
> ```lua
> Lib:EasePart(Map.Part1, Vector3.new(0, 5, 0),TweenInfo.new(1, Enum.EasingStyle.Sine, Enum.EasingDirection.Out)).Completed:Wait()
> --Do something else after the part stops moving
> ```
> 
> `Lib:MovePart() ` should remain untouched imo

useless waste of memory
just use tweenservice
