### ISSUE TITLE
[SUGGESTION] Option to disable hat/accessory particles and effects

### ISSUE THREAD

**Issue by Uncomfortable90zaza** [Tria-Studio/TRIA-Issues#24]
**Is your feature request related to a problem? Please describe.**
This is more of a problem on ROBLOX's part, but I wear hats on my avatar that use particles such as fire, and it gets in the way whenever I use first person, making certain parts in maps more difficult to see. I'm pretty sure these kind of accessories also cause lag?

**Describe the solution you'd like**
I think there should be a customizable setting that turns accessory particles on/off.

**Additional context**
![RobloxScreenShot20220612_151500850](https://user-images.githubusercontent.com/107367605/173249589-7730c298-41f4-4db3-97a5-8db38031072f.png)

A fire effect from the hat I'm wearing, while I'm trying to player LAYERS in first person.

**Comment by Ethan76167** [comment]
done for 0.8
