### ISSUE TITLE
Fix texture wraping

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#25]
Dear Tria

 When adding a texture on a small setting in liquids causes the setting to break and completely wrap on onto the lava. It literally complicates things to force people to use beams but beams are complicated. Below you can see the expectations vs reality. I think its a way you guys Handel lava meshing. And honestly its quite annoying. Please Fix it for the better of tria.

Thanks
Roberto

![image](https://user-images.githubusercontent.com/48226111/173256155-12d6f508-5da5-41b9-b9b4-fcf4de124f7f.png)
![image](https://user-images.githubusercontent.com/48226111/173256171-162733c1-7e21-4368-9cfb-688a6c52f138.png)

**Comment by Ethan76167** [comment]
What.

**Comment by Rob07erto** [comment]
![image](https://user-images.githubusercontent.com/48226111/173256322-9f91715b-fda8-44c3-bfcf-59de2e4b5c7c.png)
Roblox Studio.

![image](https://user-images.githubusercontent.com/48226111/173256324-f5da1e19-60bf-4a5b-bdb1-2c3215b625dc.png)
Tria.os

**Comment by Rob07erto** [comment]
Something with tria is causing lava to be scaled the way the user doesnt want

**Comment by Rob07erto** [comment]
and its a texture issue

**Comment by Rob07erto** [comment]
i do use the template but then i merge it to paragraph

**Comment by azzzertyy** [comment]
too many times have you not used the template, redo using the template.

**Comment by grif-0** [comment]
pretty sure this is a roblox bug with the way special meshes work anyways

**Comment by Rob07erto** [comment]
Why was mesh there in the 1st place lol

**Comment by Rob07erto** [comment]
?

**Comment by grif-0** [comment]
its how liquids are only visible on once face and the other 5 faces are transparent
