### ISSUE TITLE
[BUG] Testing: The White Screen of Death

### ISSUE THREAD

**Issue by AffluentRiley** [Tria-Studio/TRIA-Issues#28]
When you join the tria testing place there is a white screen of death. Its the same size as the map explorer so must be something to do with that.
To reproduce it join the tria testing place.
I expected to be able to play tria testing without the white screen of death.
It was on PC.
![image](https://user-images.githubusercontent.com/107575156/173891351-e08f228d-9c85-40e2-b64b-11a88c3f696d.png)

**Comment by Ethan76167** [comment]
not a bug its for testing stuff
