### ISSUE TITLE
[BUG] Testing: Toggle Perspective

### ISSUE THREAD

**Issue by AffluentRiley** [Tria-Studio/TRIA-Issues#29]
When you press "R" to go into first person you normally can press it to go back out but going back to 3rd person doesn't work anymore.
This is on PC

**Comment by Ethan76167** [comment]
looking into it

**Comment by Ethan76167** [comment]
@GlowingUmbreon can you do this one thanks

**Comment by richardios275** [comment]
not sure if you guys are looking into it, but toggle prespective doesn't work correctly which makes it difficult for me to play since I'm already used to it

**Comment by AlanTheGamer** [comment]
So what I see is that when you toggle into 1p perspective, you are in first person view along with the 1p cursor, but you can only move around as if you're in 3p(can move mouse around and have to hold right click to look around), and it only works if you use the scrollwheel to zoom out and back in.

However, once you toggle again to go back to third person, the cursor reverts to normal but you can only move around as if you have shift lock enabled.

This would not happen if you zoom out while you toggled first person but the 1p cursor would stay until you toggle again to 3p even though you already zoomed out yourself.

**Comment by Ethan76167** [comment]
Our code for this hasn't changed since the release of 0.7, soo I have no idea why this doesn't work anymore. This might be a roblox issue.

Our source code if anyone wants to fix it lol

```lua
-- Copyright (C) 2022 Tria - All rights reserved.
-- This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
-- If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

local ContextActionService = game:GetService("ContextActionService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

local PlayerModule = require(Players.LocalPlayer.PlayerScripts:WaitForChild("PlayerModule"))

local activeCameraController = PlayerModule:GetCameras().activeCameraController

local lastDistance = 32

local Settings = require(ReplicatedStorage.Settings)

local togglekeybind = Enum.KeyCode.R

local function TogglePerspective(_, inputState)
	if inputState == Enum.UserInputState.Begin then
		print(activeCameraController.inFirstPerson)
		if activeCameraController.inFirstPerson then
			
			activeCameraController:SetCameraToSubjectDistance(lastDistance)
			activeCameraController.inFirstPerson  = false
		else

			lastDistance = math.clamp(activeCameraController.currentSubjectDistance, 1, 32)
			activeCameraController:SetCameraToSubjectDistance(0.5)
			activeCameraController.inFirstPerson  = true
		end
	end
	return Enum.ContextActionResult.Pass
end

ContextActionService:BindAction("togglePerspective",TogglePerspective, false, togglekeybind)
	
```
