### ISSUE TITLE
[SUGGESTION] Cinematic Mode 

### ISSUE THREAD

**Issue by Shaadth** [Tria-Studio/TRIA-Issues#31]
Cinematic mode will remove all UI on your screen
There should be a key bind to activate it

**Comment by Rob07erto** [comment]
yes please

**Comment by Rob07erto** [comment]
we need this

**Comment by Shaadth** [comment]
also it'll remove the cursor too

**Comment by Ethan76167** [comment]
@azzzertyy ?

**Comment by azzzertyy** [comment]
planned

**Comment by Ethan76167** [comment]
is a keybind for this really a good idea? @azzzertyy

**Comment by Ethan76167** [comment]
> is a keybind for this really a good idea? @azzzertyy 

I personally feel like a bool value would work better

**Comment by azzzertyy** [comment]
im not bothered either is fine tbh

**Comment by Ethan76167** [comment]
maybe ill throw this in 0.9
