### ISSUE TITLE
[BUG]Whitelist doesn't work

### ISSUE THREAD

**Issue by AlexGam347** [Tria-Studio/TRIA-Issues#33]
Whitelist says that works, then shows an "unknown error" and when i try to load the map on tria.os it says "map loaded" but i can't see it on map list and i can't play it.

**To Reproduce**
1. Go to Map Manager 
2. Click on Whitelist
3. Paste Map Model ID
4. Go to tria.os
5. Load map
6. See error

Map whitelisted and loaded on tria.os.

![image](https://user-images.githubusercontent.com/108598462/177021209-b3fe6b7b-4741-4172-bbeb-c5fb98ad6775.png)

**Hardware Information**
 - Device: Windows 11 Pro
 - Version: 21H2

The model is on sale, i tried with normal map kit and it doesn't work.

**Comment by TBdanish** [comment]
It only works with the old map making kit

**Comment by TBdanish** [comment]
the problem is from the buttons folder in settings
get the 2nd tria.os map kit found in the toolbox for now and copy the old 'button' configuration in settings and paste it into the map's settings

**Comment by Ethan76167** [comment]
i cant repro this

**Comment by AlexGam347** [comment]
So whitelist only works on old map kit

**Comment by AlexGam347** [comment]
.
