### ISSUE TITLE
[BUG] Map sometimes loads twice?

### ISSUE THREAD

**Issue by Xeritime** [Tria-Studio/TRIA-Issues#34]
**Describe the bug**
So basically sometimes when you click a map in the map list multiple times the map will appear two times in the map queue.

**To Reproduce**
1. Open the map list
2. Open or search a map.
3. Once finished finding you desired map, click it multiple times.
4. Duplicate of map is seen on the map queue.

**Expected behavior**
I didn't expect this bug to happen.

**Screenshots**
<img width="1024" alt="Screen Shot 2022-07-03 at 1 15 15 PM" src="https://user-images.githubusercontent.com/91046851/177025946-55ea51fa-4286-42e7-b559-7a5be6665460.png">

**Hardware Information**
 - Device: macOS big Sur
 - Version: 11.6

**Additional context**
None

**Comment by Ethan76167** [comment]
fixed
