### ISSUE TITLE
Have Maps On The Map List But Still Load On Map Kit

### ISSUE THREAD

**Issue by C91OG** [Tria-Studio/TRIA-Issues#35]
**Describe the bug**
Lets Say U load **Layers** and **Dystopia** And When You Go To The Lift You Spawn In The Map Kit Instead Of The Maps

**To Reproduce**
I Havent Found How To Reproduce This Bug It Happens Randomly

**Screenshots**
![image](https://user-images.githubusercontent.com/108625633/177049485-12853b16-ae7c-4231-bce4-f475f2510cea.png)

**Hardware Information**
 - Device: pc
 - OS: windows 11

**Comment by Ethan76167** [comment]
i need some map ids to reproduce this

**Comment by C91OG** [comment]
> 

Try Electron Memories and Monoscape Thats What Me And Gab Where Playing

**Comment by Ethan76167** [comment]
works fine for me

**Comment by RayhanahyaR** [comment]
I'm pretty sure this happens when you refresh maps, the only thing that plays is Map Kit, unless you remove the map in the list and re-add it.

**Comment by Rob07erto** [comment]
Yea i get that too

**Comment by shaimoons** [comment]
> I'm pretty sure this happens when you refresh maps, the only thing that plays is Map Kit, unless you remove the map in the list and re-add it.

yes that is exactly the problem, i refreshed the maps a few times in different play sessions and it says the map is still there, yet it just loads map kit lol, so this is true

**Comment by Ethan76167** [comment]
fixed, live in all servers
