### ISSUE TITLE
Custom Themes!

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#36]
Hello, so basically i want users to be able to make their own custom themes, like in the personalization tab. 
I just don't like it how there isn't  the ability to make a custom theme, and how there isn't a perfect theme for me, and probably for others. 
This is why i am asking for customization for the theme, in which people can change their ascent colors, alt colors, font, and etc. I know its imperfect but it would be nice.
(Also i used the template, but for wording reasons i did wright it this way)

**Comment by Rob07erto** [comment]
Woops forgot to add a name. Did that

**Comment by Ethan76167** [comment]
We already declined this in discord
