### ISSUE TITLE
[BUG] Swim buttons are placed in weird spots when playing on mobile

### ISSUE THREAD

**Issue by RadicalRadio** [Tria-Studio/TRIA-Issues#37]
**Describe the bug**
The buttons which you would use to swim up, down, and to slide in maps that allow sliding have moved and are placed now in weird spots which makes it difficult to press.

**To Reproduce**
1. Join a map that uses liquids (excluding lava) and go into those liquids to enter swimming state

**Expected behavior**
Usually the buttons would be placed where they have been placed prior to this bug appearing

**Screenshots**
![Screenshot_20220704-1548072](https://user-images.githubusercontent.com/104731777/177217127-d926933b-70c2-4db0-9fff-2cac86eaada2.png)

**Hardware Information**
- Device: Mobile devices (though I am unsure if its on **all** devices or if its to ones with a certain resolution)
- Version: TRIA.os v0.8

**Comment by Ethan76167** [comment]
@GlowingUmbreon what happened here?

**Comment by Rob07erto** [comment]
i wanna swim down and jump at the same time

**Comment by Rob07erto** [comment]
but fr i went on my phone and it happened to me'
