### ISSUE TITLE
[BUG] Group buttons doesn't work properly, acting like a normal button

### ISSUE THREAD

**Issue by RadicalRadio** [Tria-Studio/TRIA-Issues#38]
Group buttons don't work like they are supposed to, requiring only one person to press when the button should take many people to press.

**To Reproduce**
1. Play any map that has group buttons present, and make sure you have enough players in the map to have the count be >1.
2. Let one person go for the button, and this should cause the button to be pressed with only one person

**Expected behavior**
Usually, group buttons have a set count. This bug makes it show the correct count but doesn't function properly, acting like a normal button.

**Screenshots**
(These aren't screenshots, but its pretty hard to tell whats wrong so I used videos instead)

https://user-images.githubusercontent.com/104731777/177219396-a0f6b918-d01b-463e-a947-ce909d75c860.mp4

https://user-images.githubusercontent.com/104731777/177219339-5163181d-c179-4cc1-8ac2-3d8064460899.mp4

**Hardware Information**
 - Device: All devices
 - OS: All OSs
 - Version [e.g. testing/stable]

**Additional context**
Nothing else to note

**Comment by Ethan76167** [comment]
fixed
