### ISSUE TITLE
[BUG]LocalMapScript can´t make a clone of a ScreenGui

### ISSUE THREAD

**Issue by AlexGam347** [Tria-Studio/TRIA-Issues#39]
**Describe the bug**
When i introduce the script: "barra = map.ScreenGui:Clone()" the console says the following text on the image

*IMPORTANT*: This error only happends on new version of map kit where the script for working is this: "local MapLib = game.GetMapLib:Invoke()()
local map = MapLib.map" instead of "local Lib = game:GetService("ReplicatedStorage").Bindables.GetMapLib:Invoke()(); local map = Lib.Map"

**To Reproduce**
1. Go to Roblox Studio
2. Load new MapKit
3. Add an ScreenGui
4. Write inside LocalMapScript: "barra = map.ScreenGui:Clone()"
5. Upload the map
6. Play the map on tria.os
7. See error (with debug mode)

**Expected behavior**
That the ScreenGui clones without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/108598462/177227896-915f0787-e4f6-4ef5-85b9-6c1b6d56aef6.png)

**Hardware Information**
 - Device: PC
 - OS: Windows 11
 - Version 21H2

**Additional context**
Full Script: 
local MapLib = game.GetMapLib:Invoke()()

local map = MapLib.map

barra = map.ScreenGui:Clone()

**Comment by Ethan76167** [comment]
does using `map` and not `Map` fix anything

**Comment by AlexGam347** [comment]
> does using `map` and not `Map` fix anything

Same error

**Comment by Ethan76167** [comment]
for now just use the old maplib ill fix this

**Comment by Ethan76167** [comment]
fixed, live in 0.8 hotfixes
