### ISSUE TITLE
[SUGGESTION] Button to reset keybinds

### ISSUE THREAD

**Issue by richardios275** [Tria-Studio/TRIA-Issues#41]
**Is your feature request related to a problem? Please describe.**
As you see, there is an issue where you cannot bind SwimDown to LeftShift since that key is binded by Shift Lock, other issues like that can happen and this is a nice convinient way to fix that without really doing anything

**Describe the solution you'd like**
Put the button at the bottom right of the settings pane and it'll reset the keybinds to how it's default

**Additional context**
![image](https://user-images.githubusercontent.com/66162489/178083111-3330ad89-4a53-40f1-ac33-765bc96156de.png)

**Comment by Ethan76167** [comment]
i guess this isnt really needed now seeing as you can bind shiftlock
