### ISSUE TITLE
[SUGGESTION] Add a setting for Unlooping BGM

### ISSUE THREAD

**Issue by KryptonForce102** [Tria-Studio/TRIA-Issues#42]
**Is your feature request related to a problem? Please describe.**
Currently ingame, it's quite tedious trying to unloop a map's BGM, take this snippet of code below that I use:
![image](https://user-images.githubusercontent.com/91935721/178083581-34905461-0b02-4f80-a7b0-8c1b5673d8d1.png)
To put it simply, `getBgm` is a function I've made which allows me to manually find the bgm of the map that's running given a SoundId.

This frustrates me because for something as simple as unlooping a BGM, it's fairly annoying to do.

**Describe the solution you'd like**
A simple solution for this could be proposed, add a new configuration folder in settings known as "Sound" or "Music", and move **all** music related properties there, this includes `Music`, `MusicVolume` and the new one which I'll call `LoopMusic`. This is a Bool attribute which when toggled off, the BGM doesn't loop!

**Additional context**
Nope!

**Comment by Ethan76167** [comment]
oh I heavily support the idea of a Music folder in settings
maybe move Music and MusicVolume to the folder, with backwards compatibility to make sure we don't break previous maps

**Comment by KryptonForce102** [comment]
> oh I heavily support the idea of a Music folder in settings maybe move Music and MusicVolume to the folder, with backwards compatibility to make sure we don't break previous maps

Definitely agree with this, unless you want to create another `.md` with code to convert configuration attributes to the new format, but I think it's best to go with backwards compatibility as some creators might not even be in the community or want to update how their map works

**Comment by Ethan76167** [comment]
We actually have our own MapConverter ingame which is called whenever a map is loaded

**Comment by Rob07erto** [comment]
![image](https://user-images.githubusercontent.com/48226111/180920035-871148d0-dc3c-4b5f-821f-7ea51cd81553.png)
would want these to be added also
