### ISSUE TITLE
[BUG] GameService Errors break current round

### ISSUE THREAD

**Issue by KryptonForce102** [Tria-Studio/TRIA-Issues#43]
**Describe the bug**
Every round, there is a likely chance that `GameService` will error and break the round. This stops the timer from running, music from playing, and other basic round features.

**To Reproduce**
This behavior is luck based, I assume this breaks more likely on larger maps because of how long they take to load.
I'm not completely sure why the bug is there, but it's most likely due to a `:WaitForChild` not being used but rather a direct index.

**Expected behavior**
I expect `GameService` to run properly and not break the round

**Screenshots**
![image](https://user-images.githubusercontent.com/91935721/178097456-5fcaa00b-0353-4ef5-8415-2f187bc10131.png)

**Hardware Information**
 - Device: `PC`
 - OS: `64-bit operating system`
 - Version: `Tria OS 0.8A.00000 (Commit dd23da5/master)`

**Additional context**
N/A

**Comment by Ethan76167** [comment]
We check for settings folder when a map is first loaded, unsure why that errors as settings folder is always loaded

**Comment by Rob07erto** [comment]
Idk, too add. Like sometimes the Game will result in error, and instead freezing tria.os, and client. Without producing an error. Like for mystical falls, everything was updated to post 0.7 kit, and worked in 0.7 but it broke without reason.

**Comment by KryptonForce102** [comment]
> We check for settings folder when a map is first loaded, unsure why that errors as settings folder is always loaded

Huh, maybe it's just a direct index? I'd assume it wouldn't break if WaitForChild was present but I can't see the game's code so I couldn't tell you

**Comment by Ethan76167** [comment]
I believe I have fixed this now
awaiting approval from qa
