### ISSUE TITLE
Freezing on spawn and you cant load or do anything

### ISSUE THREAD

**Issue by NotTwist3d** [Tria-Studio/TRIA-Issues#48]
This Bug happens sometimes, Most of my maps get affected by it. I feel like it happens when I finish a map and get ready to publish it, it might be because of an asset or a script, I don't know which one it is, But maybe y'all can find out.

**To Reproduce**
1. Go to 'N/A'
2. Click on 'N/A'
3. Scroll down to 'N/A'

**Expected behavior**
The Map Would perform perfectly fine

**Screenshots**

**H

https://user-images.githubusercontent.com/109636650/179874691-ba32243c-33ea-4c37-bf55-2509edd3bf81.mp4

hardware Information**
 - Device: Windows 11 PC
 - OS: Windows
 - Version: 11

**Additional context**
idk what to put here

**Comment by Ethan76167** [comment]
send map explorer

**Comment by NotTwist3d** [comment]
I think I fixed it

**Comment by NotTwist3d** [comment]
but ok

**Comment by Ethan76167** [comment]
what was the problem

**Comment by NotTwist3d** [comment]
you freeze completely

**Comment by Ethan76167** [comment]
no i mean how did you fix it

**Comment by NotTwist3d** [comment]
there was a script erroe

**Comment by NotTwist3d** [comment]
*error

**Comment by NotTwist3d** [comment]
lemmie check if its fixed for sure

**Comment by NotTwist3d** [comment]
its still broken

**Comment by NotTwist3d** [comment]
so i reopened it

**Comment by NotTwist3d** [comment]
ethan

**Comment by Rob07erto** [comment]
Yea the output tab doesn't give errors client side or server side. Would be nice for it actualy show them.

**Comment by Ethan76167** [comment]
> Yea the output tab doesn't give errors client side or server side. Would be nice for it actualy show them.

it was designed for map errors only

**Comment by NotTwist3d** [comment]
alr

**Comment by NotTwist3d** [comment]
any fix?

**Comment by NotTwist3d** [comment]
does anyone have a solution yet?

**Comment by NotTwist3d** [comment]
@Ethan76167 did you find a way to fix it yet? bc its still happening and i cant stop it
