### ISSUE TITLE
GUI Consistency Fix 

### ISSUE THREAD

**Issue by Roberto070** [Tria-Studio/TRIA-Issues#5]
For me, i dislike how the map loading system is  in Tria.os I feel like having like loading and searching in one page. and removing maps in one page is quite un intuitive. I would like a more unified bar to be more intuitive and make it easier. Originally in pre 0.6 it was fast loading in maps. Now its more slower and i really much dislike how it is. 

Below is a GUI that represents something i would want implemented in the game. I feel if implemented it would be way more intuitive and more faster. Call me obsessed or a bit to weird but i disliked that change ever since 0.6 was released. I asked many of times for you to change it but you denied my request. If i do recall Ethan said to be that it was a waste of space but with this it really isnt. If you can change it it would help a ton.

Thanks,
Rob07erto

![image](https://user-images.githubusercontent.com/48226111/171203680-47ac328d-1f4e-48a1-b6c0-af7871c2a465.png)

**Comment by Roberto070** [comment]
Please dont deny it please

**Comment by Ethan76167** [comment]
More info needed
bar for extra stuff could be anything

**Comment by Roberto070** [comment]
The bar for extra stuff is for features that are exclusive for each page of the map page. For example clear all maps in the "Loaded Maps", "Load Defult maps" "Map Viewer" (when you add that feature in the future) Etc.

**Comment by Ethan76167** [comment]
I think the best way to approach this would be with keybinds. We already planned the console to be a keybind, so I see no reason with making a few more keybinds for loading maps. keybind will be set to Not binded by default.

**Comment by Ethan76167** [comment]
finished

**Comment by Roberto070** [comment]
ill say this, its an attempt, but still dodges my issues. Key binds isn't what i truly asked with this request. I was asking for an more user-friendly experience. That attempt makes the gui more complicated then it needs to be. Ill let it slide for now, but when 1.0 comes around i may require this request again. Good for now ig

**Comment by Roberto070** [comment]
i shouldve worded it differently but i was asking for unity, and simplifaction hence the word "Consistancy".  I dont want tria to turn into an fe2 where the gui is unconsistant. and constnat conflicting with previous ideas, design, and wants.
