### ISSUE TITLE
More audio options

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#51]
I dislike it when there is little customization in map audio.
I would like it if there would be more option settings, and it would start from it getting its own setting folder, in this setting folder it would include -BGM ID -Is looping -time position -playback speed -is faded
BGM id would stay the same but i feel there should be the option to pick from the library and it would be listed as numbers, where there will be a list auto updated from the future tria website and will used that way to help.
Is looping would have 2 basic options No and yes, and there would be custom looping settings which allow it to be looped a certain given amount.
Time position, and playback speed self explanatory
And for is faded people would be able set it fading speed and its curve for both in and out
I feel with these changes it would make audio customization better for tria (also yes i did use the template)

**Comment by Ethan76167** [comment]
duplicate
#42
