### ISSUE TITLE
[SUGGESTION]Customisable death sounds in maps

### ISSUE THREAD

**Issue by RayhanahyaR** [Tria-Studio/TRIA-Issues#52]
**Is your feature request related to a problem? Please describe.**
Roblox’s new death sound, which as many people can agree with, sounds terrible. It wouldn’t fit very well into TRIA.os

**Describe the solution you'd like**
My suggestion is the addition of an option to change the death sound in a map to a customised audio. These should hopefully be short enough to be considered SFX. If not, audio verification could hopefully solve that.

**Additional context**
Add a string attribute in Settings.Main.
See example below
![7158770F-8E24-4A5C-9065-0B0066FEEBE5](https://user-images.githubusercontent.com/105416254/181130023-0add7bd3-e47a-4b9e-a592-b59ef1246630.png)

**Comment by Ethan76167** [comment]
bloat + impossible
