### ISSUE TITLE
[SUGGESTION] Ability to toggle lobby music

### ISSUE THREAD

**Issue by TechnocraticAviation** [Tria-Studio/TRIA-Issues#53]
**Is your feature request related to a problem? Please describe.**
A button in audio settings to turn on or off lobby music.

**Describe the solution you'd like**
A checkbox option to play or mute lobby music.

**Additional context**
get out of my head get out of my head get out of my head get out of my head get out of my head 
![image](https://user-images.githubusercontent.com/104731759/181425370-98449a64-7de3-4929-9730-44e12d241dfc.png)

**Comment by Ethan76167** [comment]
why not use music volume

**Comment by TechnocraticAviation** [comment]
> why not use music volume

That mutes the map music as well, and I want the option to just opt out the lobby music
