### ISSUE TITLE
[SUGGESTION] Momentum option for wallruns

### ISSUE THREAD

**Issue by tactaillike** [Tria-Studio/TRIA-Issues#54]
Currently, wallruns launch the player off of them perpendicular to their surface; you don't carry any momentum from the wallrun. While this behavior is fine, having a toggle (on a per wallrun basis, possibly?) to let the player carry momentum from the wallrun and launch themselves in the direction of the wallrun would allow greater flexibility when implementing them into a map.

**Comment by Ethan76167** [comment]
@GlowingUmbreon @azzzertyy Yes no?

**Comment by azzzertyy** [comment]
sure
