### ISSUE TITLE
revert tria.os swimming to 0.7 (for mobile)

### ISSUE THREAD

**Issue by Xeritime** [Tria-Studio/TRIA-Issues#55]
I don’t know if tria will do this or not but i believe the mobile swimming present in 0.8 needs to be reverted as it is quite annoying to play and i saw many people be confused and question the update so it needs to be reverted
example for the confusion of the new update is that they pretty much cant find where the buttons are (in devices like phones the buttons dont appear) so people pretty much complain about the update and my roblox friends also give hate to the swimming update as well.

**Comment by Xeritime** [comment]
oh yea extra information the complains are from people in public servers (the complains from my friends are in private servers)

**Comment by Ethan76167** [comment]
Duplicate

**Comment by Xeritime** [comment]
wdym
