### ISSUE TITLE
[SUGGESTION]Make sliding not dependant on Camera

### ISSUE THREAD

**Issue by RayhanahyaR** [Tria-Studio/TRIA-Issues#56]
**Is your feature request related to a problem? Please describe.**
Sliding in TRIA only works in one direction, the way the camera is facing. To compare to FE2, it allows sliding in any direction, no matter the camera angle. This can cause problems in maps with a 2D aspect such as Vivid, where the character would slide into the background instead of left or right:

**Describe the solution you'd like**
Simply make sliding controllable using all movement keys. Or whatever scripting stuff it is.

**Comment by KryptonForce102** [comment]
Why was this the way it was built anyway? I don't think having the player slide towards the camera at all was a good idea, but meh it's something you can get used to.

**Comment by Ethan76167** [comment]
> slide

I don't play fe2

**Comment by Ethan76167** [comment]
> Why was this the way it was built anyway? I don't think having the player slide towards the camera at all was a good idea, but meh it's something you can get used to.

I don't play fe2

**Comment by Rob07erto** [comment]
Ethan pulling the ultamate troll

**Comment by azzzertyy** [comment]
i think i prefer it being dependent on camera to be honest.
allows for more fluid gameplay, since you can move your slide mid-way through

**Comment by Ethan76167** [comment]
> 

same, i learnt to like it this way

**Comment by Rob07erto** [comment]
EHHHHHHH CAPS Lock exists

**Comment by Rob07erto** [comment]
or maybe do it a setting that a person can change either in the Map Settings or InGameSettings

**Comment by Rob07erto** [comment]
because i mean its kinda annoying, since 3rd person exists, and due to the fact you can move in a way not adjacent to the camera, so its kind of annoying imo
