### ISSUE TITLE
[BUG] The " TimeOfDay Attribute " in the settings folder is broken

### ISSUE THREAD

**Issue by arnut2020** [Tria-Studio/TRIA-Issues#57]
**Describe the bug**
After setting a new attribute called " TimeOfDay " in the studio, the time in the game ( tria.os I mean ) is not at the assigned time

**To Reproduce**
( Same thing in the ScreenShots )
1. Go to 'Roblox Studio' and go to the settings folder and make " TimeOfDay " attribute
2. After that, update the map ( so we can make sure that it's up-to-date )
3. Go to tria.os and load the map we updated ( it should be a new map to see the bug ) and play test it
4. See the error

**Expected behavior**
The map should be in nighttime

**Screenshots**
For the map, I'm making rn 
![image](https://user-images.githubusercontent.com/110468133/182388300-3288e5d3-0268-4eb5-8c80-219d0caaee9e.png)
![RobloxScreenShot20220802_203432221](https://user-images.githubusercontent.com/110468133/182389785-bdeaaffb-3d55-44ff-923b-176e08346fdf.png)
My old map of mine that used the same settings
![image](https://user-images.githubusercontent.com/110468133/182388396-7075cc1d-eaa3-4dc9-9c7e-ec6d12cf83e0.png)
![RobloxScreenShot20220802_190742299](https://user-images.githubusercontent.com/110468133/182389771-dcd0a564-5df6-4bcc-8b22-02d63da8ba6a.png)

**Hardware Information**
 - Device: PC (?)
 - OS: All
 - Version: All

**Additional context**
idk if it's really a bug or it's just the fog ( from the lighting ) that is blocking the night

**Comment by Xeritime** [comment]
yes sometimes the atmosphere (or you could call fog) blocks the time of day and can also happen to skyboxes

**Comment by arnut2020** [comment]
ok thx c:

**Comment by Enszo** [comment]
but mr white clocktime doesnt work in the mapkit settings, we have to change the value to timeofday mr white

**Comment by Enszo** [comment]
but mr white clocktime doesnt work in the mapkit settings, we need to change the value to TimeOfDay in the mapkit to make it function mr white

**Comment by Rob07erto** [comment]
Simple explamation: change "clocktime" in Lib.map.settings.main (i use lib instead of maplib) to "TimeOfDay" as "ClockTime" Doesnt work.
