### ISSUE TITLE
Gamepass idea yeah / up and down vote

### ISSUE THREAD

**Issue by Ex7remeLOL** [Tria-Studio/TRIA-Issues#6]
With the addition of themes, I think tria can release some gamepases based on it.
For example, maybe some extra themes or VIP gamepass that gives you a chat tag and exclusive themes benefit

Also, you might set some kind of script that auto-adds up and down emoji when there is a new suggestion, just like before.

**Comment by azzzertyy** [comment]
Not possible, and they're also micro transactions and we don't want that.
These will be done through the shop using XP.
Game passes are impossible because unverified servers could just give out the game pass using a script.
