### ISSUE TITLE
[SUGGESTION] More Button Types

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#61]
Buttons are quite customizable, and i have no problems because of them, but i want more button options.
These Button Options would allows for more interesting things and ill be listing them now

**UnEvent Buttons**
These buttons are not activated or deactivated by chorological order, this means they would be activated, deactivated, in random order. I feel this could be like "Lib.map.ButtonEvent("Button path", Activate/Deactivate, Type (Normal, Group, Clickable, Local)". This could allow for timed buttons where they can add more difficulty and challenge to the player,

**Locally Applied Buttons**
These buttons are only pressed locally, so no "lets be lazy and wait for another person to press it", these ones are pressed and there effects would be only shown to the client.

**Clickable Buttons**
You know how in Roblox there's this click mouse, we can use than, and make a setting where they unlike pressed via walking directly to the button, the person clicks in the range the map maker set it, so "range" would be an option in the settings.

I feel these button options can spice buttons up a bit more and hopefully these can be implemented to make buttons more customizable.

**Comment by Rob07erto** [comment]
Changed name

**Comment by azzzertyy** [comment]
id prefer if this was separated into separate issues, but local buttons are a good idea that we had a long time ago that we just never implemented apparently

**Comment by Ethan76167** [comment]
> id prefer if this was separated into separate issues, but local buttons are a good idea that we had a long time ago that we just never implemented apparently
> 
> 
> 
> also if you do not put [suggestion] in the title next time im literally just closing it

Local buttons?

**Comment by azzzertyy** [comment]
it says it in the post ethan

**Comment by Ethan76167** [comment]
> it says it in the post ethan

But that can already be done

**Comment by azzzertyy** [comment]
?
