### ISSUE TITLE
[BUG]Console GUI fails to work 

### ISSUE THREAD

**Issue by ILOVEVIVID** [Tria-Studio/TRIA-Issues#64]
**Describe the bug**
You cannot open Map Menu and Settings using the pre-set keybinds from before (Left and right on dpad)

**To Reproduce**
1. Go to TRIA.os
2. Press Left and Right on dpad, and neither should make anything happen
3. Try any button on the controller, but none will work 
4. The only current working one is Spectate (Up on dpad) Which shows that the other keybinds for the GUI is supposed to work.

**Expected behavior**

**Screenshots**

**Hardware Information**
 - Version [e.g. testing/stable]

**Additional context**

**Comment by Ethan76167** [comment]
controller players..................................
