### ISSUE TITLE
[SUGGESTION]Material Variant Support

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#66]
Since tria.os doesnt support this yet i would like there to be Material Variant Support. I would think this would behave like lighting folder and it would be easy imo.

Since all material variants go here, it would copy that material variant here in this folder [1], since those objects do exists [2]

I would want this to be in the game since it would add some more unique things. Sure we could go with texture and it wont require changes but i would want it since it would add more customization to maps since PBR allows light to work differently in the objects. Hopefully it gets added i would want it in the game

1) ![image](https://user-images.githubusercontent.com/48226111/184260409-e3ddfac4-652d-4d36-8941-35c48c23f4aa.png)
2) ![image](https://user-images.githubusercontent.com/48226111/184260278-b88f7a5d-cc51-49c7-b6ed-dbea9c608a71.png)

**Comment by Ethan76167** [comment]
maybe in the future

**Comment by Rob07erto** [comment]
So will it be planned?
