### ISSUE TITLE
[SUGGESTION]Trusted Users Features

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#67]
Since tria really doesn't have Trusted Users  Features i feel we can add them, and since its planned i would want it. 
My Requests is for server owners to allow people to set other users to Edit the Map List, Kick people, and Mute, It would either be its own menu or in the map list itself.  Here would be my gui concept and i hope it gets in. 
![image](https://user-images.githubusercontent.com/48226111/184457548-447e4754-9f92-4b98-b995-d3ade8cc114a.png)

**Comment by RayhanahyaR** [comment]
It's probably best to just have map list permissions, as that's what people want most of all.

**Comment by Rob07erto** [comment]
For me, when tria grows. When people do host events like "Tria Escape VIP Gamenight" people would want to moderate others in their private servers. Look at FE2CM there were custom admin panels and it is quite inconvenient to have to script something, when tria could include it self. Even tho there will be a kick voting system, it isn't convenient for vip owners. and also there are games where retards cause false bans. So im kinda wanting it.

**Comment by Rob07erto** [comment]
And trust me ive been there with games with vote kick systems, and ive been kicked like about 10? times for doing nothing wrong
