### ISSUE TITLE
[BUG]Map Script fails to load the 1st time

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#68]
Idk if its me but ever since 0.8.5 released the map script for Dark industry doesnt load the 1st time and only does the second time.

1. Load Id of my Testing Id:9964754914
2. Play map
3. See error, restart the charecter
4. Play again

**Expected behavior**
Door would open

**Screenshots**
![image](https://user-images.githubusercontent.com/48226111/184504713-aaf054db-756a-40e2-9615-856ca79ffa0e.png)
![image](https://user-images.githubusercontent.com/48226111/184504724-192e9996-d49a-42de-8244-094bbd12176c.png)
![image](https://user-images.githubusercontent.com/48226111/184504737-ebdf85a2-3107-4a8e-93d4-baef1e5a6846.png)

**Hardware Information**
 - Device: Hp Pavilion 15: Ec00003ca
 - OS: Windows 11 Home
 - Version TRIA.OS Escape V0.8.5 Main

**Comment by RadicalRadio** [comment]
I can't seem to reproduce this - I've loaded the map many times and the door opens each attempt

**Comment by Rob07erto** [comment]
weird also ive been changing things with that id so best idea to close  issue
