### ISSUE TITLE
[SUGGESTION] To be able to exit a map. 

### ISSUE THREAD

**Issue by Lu-c4** [Tria-Studio/TRIA-Issues#69]
This suggestion is not related to a problem.
It would be good if you could exit a map if you no longer wished to do play it.

It would be good to have a button in a corner at the bottom of the screen to exit a map.

**Comment by RayhanahyaR** [comment]
Press esc.
Press R.
Press enter.
or if you're on mobile press the button in the top left and press the button that says 'Reset'.
done. close this.
