### ISSUE TITLE
Tria.os console has placeholder text.

### ISSUE THREAD

**Issue by C91OG** [Tria-Studio/TRIA-Issues#71]
The console says tria is in 0.5.1 while tria just realesed 0.8.6!

To re make this bug
Open map menu
Click console
And u should see a version thingy like this

![IMG_20220815_201500](https://user-images.githubusercontent.com/108625633/184686203-b3907688-00d9-433a-a426-cd021f8d7096.jpg)

Phone : xiaomi redmi note 10s
Os : miui
Version : adrod 12 real

**Comment by Luca-underscore** [comment]
![tria issue evidence 1](https://user-images.githubusercontent.com/104580172/184712384-3a285344-e7f7-4047-b0b6-ce345fbe6463.png)
i can confirm the issue.

**Comment by Ethan76167** [comment]
we literally just set it to a random number
