### ISSUE TITLE
[SUGGESTION]Sensitivity slider for mobile

### ISSUE THREAD

**Issue by LOL1ES** [Tria-Studio/TRIA-Issues#73]
It would help for people who aren’t used to the higher sensitivity

**Comment by Ethan76167** [comment]
use roblox settings?????

**Comment by LOL1ES** [comment]
Mobile Roblox settings doesn’t have camera sensitivity for some reason

**Comment by LOL1ES** [comment]
![A70979FD-48D4-47CF-A691-F398D9FA91D6](https://user-images.githubusercontent.com/111414696/185306535-82970706-336b-40a8-8cc1-013b53875d5c.jpeg)

**Comment by Ethan76167** [comment]
nice one roblox

**Comment by Ethan76167** [comment]
@GlowingUmbreon so should we add this yes or no
