### ISSUE TITLE
[SUGGESTION]Sliding direction should be based on where the player is facing

### ISSUE THREAD

**Issue by DONUTSLM** [Tria-Studio/TRIA-Issues#74]
Currently, sliding direction is based on what direction the camera is facing. This is kind of weird for sliding direction because to slide under an obstacle, you need to face your camera toward the obstacle.

It's be better and easier to control sliding if it was based on what direction the player was facing. This way, players can just collide with the obstacle, then slide under it and wouldn't have to move their camera.

There's also the option of making it a setting, either for local players or for map makers to set for their maps (would recommend the former).

**Comment by RadicalRadio** [comment]
I think this was already suggested a while ago
https://github.com/Tria-Studio/TRIA-Issues/issues/56
