### ISSUE TITLE
Fix map validation on map manager.

### ISSUE THREAD

**Issue by DONUTSLM** [Tria-Studio/TRIA-Issues#75]
Currently, the TRIA.os game doesn't seem to support the Spawn not being a direct child of the map model.

So then why is the Spawn inside the Special folder when loading in the map kit?
<img width="137" alt="image" src="https://user-images.githubusercontent.com/75456372/185512951-81d509f0-0977-4e9c-9dac-e54c3f4c39da.png">

It should be moved to be a direct child of the model in the default kit.

**Comment by Ethan76167** [comment]
> This happens because we are yet to update mapkit to support these changes.

putting spawn in special currently doesnt work for some reason 
![image](https://user-images.githubusercontent.com/72885654/185794595-b6c04753-b534-48ad-af69-42b08f4734f4.png)
