### ISSUE TITLE
[BUG]Swim and dive buttons are switched.

### ISSUE THREAD

**Issue by DONUTSLM** [Tria-Studio/TRIA-Issues#76]
![DF7EF995-90D8-49C7-94F0-5F20D71F5598](https://user-images.githubusercontent.com/75456372/185756028-71da6d41-401e-4bd8-8525-eb3459a25331.jpeg)

On mobile, the button on the top should be for diving and the button on the bottom should be for swimming up (because it matches the jump button). But in TRIA.os, they are switched. Now the dive button has an up arrow on it, which is confusing.

The bottom button should swim up and the top button should dive down. The top button should also have some sorr of symbol or text to show that it is for diving.

**Comment by Ethan76167** [comment]
fixed in 0.9
