### ISSUE TITLE
[BUG]Spawn's location in the mapkit makes the map unloadable

### ISSUE THREAD

**Issue by dx-rift** [Tria-Studio/TRIA-Issues#77]
**Describe the bug**
The Spawn in mapkit is located within the "Special" Folder however, when attempting to load it, it comes up with an error instead.

**To Reproduce**
1. Don't change Spawn's Parent (Leave it as Special).
2. Attempt to Load Map.
3. See error.

**Expected behavior**
The map to be loaded without any errors.

**Screenshots**
https://user-images.githubusercontent.com/111685972/185788783-935ff8e7-2bd1-4115-8918-af9535782d98.png
The error message that occurs.

**Hardware Information**
 - Device: Surface Pro 8
 - OS: Windows
 - Version 21H2

**Additional context**
I haven't tested if the map can load if Spawn is the child of any other object, only as the Special folder and the direct child of the map (which works).

**Comment by Ethan76167** [comment]
fixed 0.9
