### ISSUE TITLE
[SUGGESTION]Make the map buttons bigger

### ISSUE THREAD

**Issue by DONUTSLM** [Tria-Studio/TRIA-Issues#79]
The delete and info button above a map on the map screen are WAY too small. They're unnecessarily difficult to press, especially on mobile devices.

The simple solution is to make the buttons bigger. I don't see why they can't be since there's so much empty space around them. Maybe make the hitboxes be as big as the rectangle that they're in (split in half so both buttons would have the same hitbox).

Here's my epic journey trying to delete all maps except Aurelius.
https://user-images.githubusercontent.com/75456372/186058650-a0de73bc-153a-4d4b-9bd4-42ec87468a19.MOV

It took 38 seconds.

**Comment by Ethan76167** [comment]
there's major ui improvements in 0.9(next update)
