### ISSUE TITLE
[BUG] LeftShift on keybindings not working.

### ISSUE THREAD

**Issue by mmicoof2** [Tria-Studio/TRIA-Issues#81]
the bug makes me unable to set the keybind back to leftshift in the control setting due to the shiftlock being permanently on, even if I try to turn it off in the roblox setting in game. So that means I can't set the hotkey on leftshift (and probably rightshift idk), so I'm literally having to play with another hotkey that I'm not used to using wit

https://user-images.githubusercontent.com/112321889/187071860-8db32bef-b0ae-44f7-9ac9-c6e52d94faf3.mp4

**Comment by azzzertyy** [comment]
no way to fix

**Comment by Ethan76167** [comment]
> no way to fix

i believe cause its already binded, also how does fe2 counter this then

**Comment by grif-0** [comment]
> i believe cause its already binded, also how does fe2 counter this then

you can unbind leftshift from shiftlock

**Comment by KryptonForce102** [comment]
Fixed in 0.9
