### ISSUE TITLE
[BUG]Tria Scripts arent loading in newer ids

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#82]
Tria Scripts aren't loading in newer ids
To reproduce the this bug
1. Load The "RFA Public Testing Id: 9964754914"
2. Play the Map

Within this script it shows that the map script is working fine but in my it isn't loading the scripts
![image](https://user-images.githubusercontent.com/48226111/187811297-51ca172e-57f7-4bd1-a764-87531e2830cd.png)

Device info:
Device: Hp Pavilion 15 ec0003ca
OS: Windows 11

Note a few other Map Creators which are "Logzy" and "Dogeify" are having the same issue so i am Assuming this is Tria.OS or ROBLOX fault.

**Comment by Rob07erto** [comment]
Like idk whats causing this

**Comment by Ethan76167** [comment]
not our problem
