### ISSUE TITLE
[BUG] Overlapping Alerts

### ISSUE THREAD

**Issue by MADB0SS** [Tria-Studio/TRIA-Issues#85]
**Describe the bug**
Alerts will sometimes overlap with each other creating a jumble of text,

**To Reproduce**

The bug is extremely weird to replicate, but my guess is that alerts do not move down in order properly and cause multiple to do so. The following code will replicate the behavior (Testing game only):
`MapLib:Alert("Alert #1", Color3.new(1, 1. 1), 6)
task.wait(2)
MapLib:Alert("Alert #2", Color3.new(1, 0, 0), 2)`

**Expected behavior**

The alerts should not overlap and should look normal, one on top of the other. Self-explanatory.

**Screenshots**
![image](https://user-images.githubusercontent.com/67429094/188720217-3ed9a0b3-f503-4db8-8041-b9e3f1401c24.png)
Video link in QA chat: https://discord.com/channels/565208753914249256/967190295953440849/1016788612962066452

**Hardware Information**
 - Device: PC
 - OS: Windows
 - Version: Testing

**Additional context**

Please ping me on discord if the issue is not able to be replicated with the provided code. I will supply the specific map used to report this bug.

**Comment by Ethan76167** [comment]
This has happened since day one and I have no idea why

**Comment by KryptonForce102** [comment]
> This has happened since day one and I have no idea why

~~fix it nerd~~
Kidding will see if I can fix or find out why it's caused

**Comment by KryptonForce102** [comment]
I believe I have fixed this, will get QA to confirm later on.
