### ISSUE TITLE
Sliding Has A Bug!?!?!?

### ISSUE THREAD

**Issue by C91OG** [Tria-Studio/TRIA-Issues#86]
**Sliding Bug**
If you enabe Debug and spam the key you use to slide soo many error codes are gonna pop up!

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Misc'
3. And Enable 'Debug'
4. And Then Spam Your Slide Button
5. See Error

**Expected behavior**
Soo many error popups are gona pop up!

**Hardware Information**
 - Device: [Laptop]
 - OS: [Windows 11]
 - Version [Stable]

**Comment by Ethan76167** [comment]
Provide video

**Comment by MADB0SS** [comment]
the bug is fixed in testing already no need to fix. i noticed it when testing a map and i did experience the issue, but as I said, it is already fixed in the testing game.

**Comment by Ethan76167** [comment]
fixed
