### ISSUE TITLE
[SUGGESTION]Different Map Image Types

### ISSUE THREAD

**Issue by Rob07erto** [Tria-Studio/TRIA-Issues#87]
A Feature i always wanted for tria was to have different map image types, Right now there is only 1 but i want 3 . Since Map info has been started to be developed i had 1 major issue with it that the banner crops some shit and reduces some of the image, which is not convenient. And also since map loading screen has started it text on those images can be redundant. 

  So what I am suggesting is there to be 3 map image types: Map Banner, Map Thumbnail, and Map Loader Images, in which it will be in the Map.Settings.Main area and in the docs it will show the recommended image size for the map image size to be!

**Comment by Ethan76167** [comment]
I dont understand.

**Comment by Rob07erto** [comment]
Bruh
