### ISSUE TITLE
Make ExitRegion usable for maps that doesn't have buttons

### ISSUE THREAD

**Issue by coderheck** [Tria-Studio/TRIA-Issues#89]
This request was made due to the fact that everytime I put a single button in my map, the game sorta break when you load in the map, if you respawn you will just ragdoll your avatar and nothing else, you can't return to lobby which requires you to rejoin.

The solution to this is to somehow make the MapLib accepts the player to "survive" the map after touching the ExitRegion w/o pressing any buttons. This could be done by putting another attribute in the "Main" folder of the "Settings" folder which acts as a switch to allow whether a map can be survived w/o any buttons or not.

**Comment by Ethan76167** [comment]
maplib:Survive(player: Player)
