### ISSUE TITLE
[SUGGESTION] FREECAM

### ISSUE THREAD

**Issue by KrazedKiefer** [Tria-Studio/TRIA-Issues#90]
My suggestion is to add a **freecam** option, it would be togglable in the **misc settings** like debug mode. This could benefit players and youtubers in many ways, youtubers could use it to find a good spot in the map to take a photo of and use it for a thumbnail and players could use it to see mistakes they made in maps or to take a photo of a map to use as a wallpaper. It would also disable the UI like cinematic mode, but also disable the **roblox UI** and **force the player into first person**. Maybe even hide the cursor, it's your choice. Anyways that's the feature I came up with, hope you like it.

**Comment by coderheck** [comment]
isnt disabling roblox GUI is not possible by script

**Comment by grif-0** [comment]
You can disable every gui on the screen except for the menu button in the top left corner

**Comment by KrazedKiefer** [comment]
you know I never thought of that

**Comment by azzzertyy** [comment]
probably bloat to implement this, would be better off as a custom map so that it doesnt take up space in our code

**Comment by KryptonForce102** [comment]
Seems like a way to find hidden rooms and cheats in maps (if that is implemented). It would be nice but could ruin a few maps with secret pathways or buttons.

**Comment by KrazedKiefer** [comment]
i thought of that but now i realize that
