### ISSUE TITLE
[BUG]F1,F2,F3 keys not working

### ISSUE THREAD

**Issue by JackDoeaw** [Tria-Studio/TRIA-Issues#91]
**Describe the bug**

**To Reproduce**
1. Join the game
2. Press F3
3. Settings tab wont open

**Expected behavior**
Well I pressed F2 to spectate and it didn't open;
Same thing with F3, I pressed to configure my fov and it also did not open.

**Screenshots**
(none)

**Hardware Information**
 - Device: PC
 - OS: WIN11
 - Version STABLE

**Additional context**
(none)

**Comment by KryptonForce102** [comment]
I think someone may have removed this. Will check

**Comment by Ethan76167** [comment]
0.9.1
