### ISSUE TITLE
[BUG]Spawnkill

### ISSUE THREAD

**Issue by JackDoeaw** [Tria-Studio/TRIA-Issues#92]
**Describe the bug**
You literally just keep dying in the elevator until the round starts or smth

**To Reproduce**
1. Probably die to a killblock (not sure)
2. Then just keep getting spawnkilled 

**Expected behavior**
Well I died to the kill block and just expected to respawn normally

**Screenshots**
https://user-images.githubusercontent.com/53980898/192027047-189f6247-0af3-4eb3-af0e-baca07af29b3.mp4

**Hardware Information**

 - Device: PC
 - OS: WIN11
 - Version STABLE

**Additional context**
(none)

**Comment by grif-0** [comment]
Fixed, waiting for pr to merge.

**Comment by grif-0** [comment]
@azzzertyy @Ethan76167 @GlowingUmbreon i cant close issues can you close this

**Comment by KryptonForce102** [comment]
**Fixed in 0.9.1**
