### ISSUE TITLE
[BUG]Loading issue

### ISSUE THREAD

**Issue by JackDoeaw** [Tria-Studio/TRIA-Issues#93]
**Describe the bug**
The map starts without you (or more people) load properly

**To Reproduce**
1. Get a "laggy" map (like layers or endzone)
2. Just wait in the lift
3. Small chance of the map loading without you or more people 

**Expected behavior**
Well that the loading screen would go away and I would be able to play normally

**Screenshots**

https://user-images.githubusercontent.com/53980898/192027514-97bf3864-63c7-4568-bdf8-9097026a7c9b.mp4

**Hardware Information**
 - Device: PC
 - OS: WIN11
 - Version STABLE

**Additional context**
(none)

**Comment by grif-0** [comment]
Does this happen when you are the only person in the lift or when there's multiple people in the lift?

**Comment by KryptonForce102** [comment]
**Fixed in 0.9.1**
