### ISSUE TITLE
[BUG] Spectating

### ISSUE THREAD

**Issue by Jaylxnn** [Tria-Studio/TRIA-Issues#94]
**Describe the bug**
When you join the game while round in progress, spectating doesn't show anyone.

**To Reproduce**
1. Join a game while a round in progress
2. Click on spectate icon

**Expected behavior**
You should see the player including spectate button

**Screenshots**
https://user-images.githubusercontent.com/52697072/192033258-8481cd50-fb9c-4b95-a6b6-c50b867f098f.mp4

**Hardware Information**
 - Device: PC
 - OS: Windows 11
 - Version: STABLE

**Additional context**
none.

**Comment by KryptonForce102** [comment]
**Fixed in 0.9.1**
