### ISSUE TITLE
[BUG]I dont even know

### ISSUE THREAD

**Issue by JackDoeaw** [Tria-Studio/TRIA-Issues#95]
**Describe the bug**
So I was just playing normally
until the round loaded
basically I CANT MOVE and I CANT DIE aswell

**To Reproduce**
1. It just happens

**Expected behavior**
I just wanted to play

**Screenshots**
https://www.youtube.com/watch?v=AxHAuygIn0k

**Hardware Information**
 - Device: PC
 - OS: WIN11
 - Version STABLE

**Additional context**
(none)

**Comment by Ethan76167** [comment]
See if you can still reproduce this

**Comment by KryptonForce102** [comment]
**Fixed in 0.9.1**
