### ISSUE TITLE
[BUG] Body is still anchored after an error

### ISSUE THREAD

**Issue by Jaylxnn** [Tria-Studio/TRIA-Issues#96]
**Describe the bug**
The error keeps happening from this map called **Mystical Realm ( I )**. Once at the end (getting teleported to the Exit), the error happens and you won't be able to play unless you rejoin.

**To Reproduce**
1. Play **Mystical Realm**
2. Get to the exit
3. You should see the error on console log

**Expected behavior**
Should let you play the next map without any error.

**Screenshots**
https://user-images.githubusercontent.com/52697072/192043036-3af973a4-28e3-43e6-a44f-3dc919322b12.png

**Hardware Information**
 - Device: PC
 - OS: WIN11
 - Version stable

**Additional context**
After playing **Mystical Realm ( I )**, you don't get teleported to the next map. (Not sure for others but happened to me)

**Comment by grif-0** [comment]
If this only happens in mystical realm, are you sure this is not an issue with the map?

**Comment by KryptonForce102** [comment]
Will check this out

**Comment by KryptonForce102** [comment]
This mainly occurs when the map has no **Exit** folder inside the Special Folder. Meaning `Special -> Exit` doesn't exist. This is an issue with the map itself.

**Comment by Jaylxnn** [comment]
Ah, some maps being played keeps doing the anchor stuff so I guess we wait until they are updated.

**Comment by KryptonForce102** [comment]
**Fixed in 0.9.1**
