### ISSUE TITLE
Monovoid's camera is very annoying

### ISSUE THREAD

**Issue by DONUTSLM** [Tria-Studio/TRIA-Issues#99]
Monovoid's camera switching is very annoying for two-finger mobile players. Zooming out the camera takes too long and is extremely hard to do immediately. The easiest solution would be to make it so that the camera goes back to where it was before after the first person part. There's literally a computer keybind that can do this, so I don't see why Monovoid can't just use the same script as that.

Video of Monovoid's most annoying part (it's possible but super annoying)
https://user-images.githubusercontent.com/75456372/192116009-bdd63726-0b47-46af-9b1c-24c644def778.MOV

**Comment by nikitus2000** [comment]
lol
